services:
  - type: web
    name: web_bingo          # Matches Render service name (use lowercase, no spaces)
    env: python
    runtime: python3.9           # Compatible with geopandas, osmnx
    plan: free                   # Or starter/paid if needed
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn BingoWeb:app --workers 1 --timeout 120
    autoDeploy: true             # Deploy on Git push